[site]: datascience
[post_id]: 126458
[parent_id]: 
[tags]: 
pos_label=1 is not a valid label. Should be one of [2,4]

I am trying to retrieve my precision score but I am getting an error as follows: pos_label=1 is not a valid label. It should be one of [2 ,4] And here is the code I have written: from sklearn.metrics import precision_score con_matrix = metrics.confusion_matrix(y_test, lrcv_predict_train) print(con_matrix) #[TP | FP] #[FN | TN] class_report = metrics.classification_report(y_test, lrcv_predict_train) print(class_report) precision_score(y_test, lrcv_predict_train, average = None) print("Precision score: {}".format(precision_score(y_test, lrcv_predict_train), pos_label = 2)) As you c an see, I have changed the pos_label to 2, but it is still giving me the error. I have also tried putting it in quotations, replacing 2 with 4, putting brackets around 2 or 4, and putting them in quotes but I still get the same error. I've looked around but have not encountered my particular dilemma, and all the answers of questions similar to my own have not worked for me. Can someone tell me what I've missed or have done incorrectly? Thank you.
