[site]: datascience
[post_id]: 115304
[parent_id]: 
[tags]: 
ValueError: dtype='numeric' is not compatible with arrays of bytes/strings.Convert your data to numeric values explicitly instead

I am new to machine learning model deployment. In a sequence, local system rises an error while running "app.py" file, that is: "ValueError: dtype='numeric' is not compatible with arrays of bytes/strings.Convert your data to numeric values explicitly instead."
