[site]: stackoverflow
[post_id]: 334781
[parent_id]: 334780
[tags]: 
Yes, destructors will be called as expected, the same as if you exited the scope early due to an exception. Standard 6.6/2 (Jump statements): On exit from scope (however accomplished), destructors are called for all constructed objects with automatic storage duration that are declared in that scope, in the reverse order of their declaration.
